import keyMirror from "react/lib/keyMirror";

export default keyMirror({
  // auth actions
  LOGIN_ERROR: null,
  LOGIN_RESPONSE: null,
  LOGIN_REQUEST: null,
  LOGOUT_ERROR: null,
  LOGOUT_RESPONSE: null,
  LOGOUT_REQUEST: null,
  OAUTH_ERROR: null,
  OAUTH_RESPONSE: null,
  OAUTH_REQUEST: null,
  SIGNUP_ERROR: null,
  SIGNUP_RESPONSE: null,
  SIGNUP_REQUEST: null,

  // product actions
  PRODUCT_CREATE_ERROR: null,
  PRODUCT_CREATE_RESPONSE: null,
  PRODUCT_CREATE_REQUEST: null,
  PRODUCT_DESTROY_ERROR: null,
  PRODUCT_DESTROY_RESPONSE: null,
  PRODUCT_DESTROY_REQUEST: null,
  PRODUCT_LOAD_ERROR: null,
  PRODUCT_LOAD_RESPONSE: null,
  PRODUCT_LOAD_REQUEST: null,
  PRODUCT_UPDATE_ERROR: null,
  PRODUCT_UPDATE_RESPONSE: null,
  PRODUCT_UPDATE_REQUEST: null,

  // transaction actions
  CLIENT_TOKEN_ERROR: null,
  CLIENT_TOKEN_RESPONSE: null,
  CLIENT_TOKEN_REQUEST: null,
  TRANSACTION_CREATE_ERROR: null,
  TRANSACTION_CREATE_RESPONSE: null,
  TRANSACTION_CREATE_REQUEST: null,
  TRANSACTION_LOAD_ERROR: null,
  TRANSACTION_LOAD_RESPONSE: null,
  TRANSACTION_LOAD_REQUEST: null
})
