import keyMirror from "react/lib/keyMirror";

export default keyMirror({
  AUTH_REQUEST_ERROR: null,
  AUTH_REQUEST_SUCCESS: null,
  CLIENT_TOKEN_REQUEST_ERROR: null,
  CLIENT_TOKEN_REQUEST_SUCCESS: null,
  PRODUCT_CREATE_ERROR: null,
  PRODUCT_CREATE_RESPONSE: null,
  PRODUCT_CREATE_REQUEST: null,
  PRODUCT_DESTROY_ERROR: null,
  PRODUCT_DESTROY_RESPONSE: null,
  PRODUCT_DESTROY_REQUEST: null,
  PRODUCT_LOAD_ERROR: null,
  PRODUCT_LOAD_RESPONSE: null,
  PRODUCT_LOAD_REQUEST: null,
  PRODUCT_UPDATE_ERROR: null,
  PRODUCT_UPDATE_RESPONSE: null,
  PRODUCT_UPDATE_REQUEST: null,
  TRANSACTION_REQUEST_ERROR: null,
  TRANSACTION_REQUEST_SUCCESS: null
})
