import keyMirror from "react/lib/keyMirror";

export default keyMirror({
  AUTH_ERROR: null,
  AUTH_RESPONSE: null,

  CLIENT_TOKEN_ERROR: null,
  CLIENT_TOKEN_RESPONSE: null,
  CLIENT_TOKEN_REQUEST: null,

  PRODUCT_CREATE_ERROR: null,
  PRODUCT_CREATE_RESPONSE: null,
  PRODUCT_CREATE_REQUEST: null,
  PRODUCT_DESTROY_ERROR: null,
  PRODUCT_DESTROY_RESPONSE: null,
  PRODUCT_DESTROY_REQUEST: null,
  PRODUCT_LOAD_ERROR: null,
  PRODUCT_LOAD_RESPONSE: null,
  PRODUCT_LOAD_REQUEST: null,
  PRODUCT_UPDATE_ERROR: null,
  PRODUCT_UPDATE_RESPONSE: null,
  PRODUCT_UPDATE_REQUEST: null,

  TRANSACTION_CREATE_ERROR: null,
  TRANSACTION_CREATE_RESPONSE: null,
  TRANSACTION_CREATE_REQUEST: null,
  TRANSACTION_LOAD_ERROR: null,
  TRANSACTION_LOAD_RESPONSE: null,
  TRANSACTION_LOAD_REQUEST: null
})
